# This assembles data for the parking garage project
# SFpark distributes one CSV file per garage, with some garage-level data in the header:
# https://www.sfmta.com/getting-around/drive-park/demand-responsive-pricing/sfpark-evaluation
# Convert this to a single table.

# You do not need to run this script; it has already been run and the output is in data/sfpark.csv

library(tidyverse)

# This function reads an SFPark CSV, which have an esoteric format with the first
# two rows describing the data, and the usage_type row mostly containing blanks that must
# be filled from the most recent non-blank row.
read_sfpark = function(filename) {
  # read the header (info about the file, on line 2). Skip line 1, and retrieve only line 2 (now the first row)
  hdr = read_csv(filename, col_names=F, skip=1)[1,]
  
  # extract the facility and district from the header. X2 and X6 are autogenerated column names from read_csv,
  # since we told it not to read column names from the file (col_names=F). [[1]] selects the first value as a scalar.
  fac = hdr$X2[[1]]
  district = hdr$X6[[1]]
  
  # read the rest of the data, skipping the header, and retaining only non-empty columns
  data = read_csv(filename,
                  skip=2, col_select=all_of(c("Usage Type", "Date", "Total Entries", "Total Exits")))
  
  # add colums for facility and district
  data$facility = fac
  data$district = district
  
  # Fill usage type down
  data = fill(data, any_of("Usage Type"))
  
  # rename columns to be easier to use
  data = rename(data, all_of(c(
    usage_type="Usage Type",
    date="Date",
    entries="Total Entries",
    exits="Total Exits"
  )))
  
  # "return" the data as the value of this function
  return(data)
}

# read all of the files
data = bind_rows(lapply(Sys.glob("sfpark/data/raw/*.csv"), read_sfpark))

write_csv(data, "sfpark/data/sfpark.csv")
